### ISSUE TITLE
Why the marginals for 'a' is not normalized in the example?

### ISSUE THREAD

**Issue by linhaojia13** [mbforbes/py-factorgraph#5]
After running the example, the marginal for 'b' is  normalized while the one for 'a' is not normalized. Why?

```
Marginals for RVs:
a
         0       0.07
         1       0.5366666666666666
b
         0       0.3406593406593406
         1       0.2967032967032967
         2       0.36263736263736257
```

**Comment by mbforbes** [comment]
Hi @linhaojia13, thanks for the question.

They are not normalized because the argument `normalize` was not passed to `print_rv_marginals()`

If you check out the doc string for the code that prints that:

```py
    def print_rv_marginals(self, rvs=None, normalize=False):
        '''
        Displays marginals for rvs.

        The marginal for RV i is computed as:

            marg = prod_{neighboring f_j} message_{f_j -> i}

        Args:
            rvs ([RV], opt): Displays all if None
            normalize (bool, opt) whether to turn this into a probability
                distribution
        '''
```

If we change the example to instead call `g.print_rv_marginals(normalize=True)`, then they are normalized:

```txt
Marginals for RVs (normalized):
a
	 0 	 0.11538461538461539
	 1 	 0.8846153846153845
b
	 0 	 0.34065934065934067
	 1 	 0.29670329670329676
	 2 	 0.3626373626373626
```

I agree this can be confusing, since `b` happens to be normalized based on the algorithm. I've updated the example and docs to print the normalized RVs to prevent future confusion. Hope this helps.

**Comment by linhaojia13** [comment]
Thanks a lot for your detailed reply and code updation, and most of my confusion are cleaned. Now I want to dig into the codes to find why the 'b' happens to be normalized. Thank you!
