### ISSUE TITLE
Why 'a' send message to 'f(a)'?

### ISSUE THREAD

**Issue by linhaojia13** [mbforbes/py-factorgraph#6]
![图片](https://user-images.githubusercontent.com/38275612/180189518-c34aa301-c535-4992-8214-36b54a7526ad.png)

Thank you very much for your codes, it really help my research a lot!

In my understanding, the factor graph in the example is shown above. According the sum-product algorithm, if we want to compute the marginal probability, the messages from the factors to the rvs need to be computed. But in the printed results of the example, the messages from the factors to the rvs are computed. Why? Is this redundant?

![图片](https://user-images.githubusercontent.com/38275612/180191154-8dc2cc12-8880-4528-a2d9-8e0b99a87bed.png)

**Comment by mbforbes** [comment]
Hi @linhaojia13, I'm glad to hear this is helping your research.

I'm having a bit of trouble understanding your question. You wrote

> the messages from the factors to the rvs need to be computed

and then

> messages from the factors to the rvs are computed

Both of these refer to the same direction. Are you asking about the opposite direction (messages from RVs to factors)?

Truth be told, it's been six years since I worked with or thought about factor graphs, so I don't remember details here. I believe that I am printing all outgoing messages — even ones that you won't care about for the output — simply as an understanding / debugging aid.

Let me know if this clarifies anything, or if I'm missing your question.

**Comment by linhaojia13** [comment]
I'm sorry that I made a mistake in writing my question. But Fortunately, you still get my original question...hhhh
> Both of these refer to the same direction. Are you asking about the opposite direction (messages from RVs to factors)?

Your wrote
>I am printing all outgoing messages — even ones that you won't care about for the output — simply as an understanding / debugging aid.

This shows some possibility of my opinion that **the messages from RVs to factors may be redundant**. I will dig into the codes to check this.

Thank you very much!
